name: pos_app
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=3.4.1 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.6
  dio: ^5.4.3+1
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  flutter_easyloading: ^3.0.5
  flutter_flavor: ^3.1.3
  flutter_form_builder: ^9.3.0
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.4.0
  form_builder_validators: ^10.0.1
  get: 4.6.6
  get_storage: ^2.1.1
  infinite_scroll_pagination: ^4.0.0
  intl: ^0.19.0

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_lints: 4.0.0
  flutter_test:
    sdk: flutter

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/icon_launcher.png"

flutter_native_splash:
  color: "#ffffff"
  image: "assets/images/icon_launcher.png"
  android: true
  ios: true

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/images/
    - assets/fonts/
  fonts:
    - family: Lato
      fonts:
        - asset: assets/fonts/Lato/Lato-Regular.ttf
        - asset: assets/fonts/Lato/Lato-Bold.ttf
          weight: 700
        - asset: assets/fonts/Lato/Lato-Italic.ttf
          style: italic
